-- Tack Rack — pending database migrations
-- Generated 2026-09-22 13:20 by bin/export-migrations-sql.php. Do not edit by hand.
--
-- Import through phpMyAdmin: select the site database, open the Import tab,
-- choose this file, and run it. It contains, in this order:
--
--   2026_08_18_000003_location_and_logo.sql
--   2026_08_30_000004_seo_share_card.sql
--   2026_09_22_000005_staff_expertise_wording.sql
--   2026_09_22_000006_single_line_address.sql
--   2026_09_22_000007_instagram.sql
--
-- Every statement in here is safe to run more than once, so importing it twice
-- changes nothing the second time.
--
-- It only touches the `settings` table and the `migrations` bookkeeping table.
-- No products, orders, customers or quotes are read or written.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `migrations` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename`   VARCHAR(190) NOT NULL,
  `applied_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_migrations_filename` (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================================
--  2026_08_18_000003_location_and_logo.sql
-- =====================================================================

-- =====================================================================
--  Real location details, taken from the Tack Rack Ltd Google Business
--  Profile, plus the logo as the default share image.
--
--  These overwrite the placeholders seeded at build time, so this file uses
--  ON DUPLICATE KEY UPDATE rather than IGNORE. Anything you have since
--  corrected by hand in Admin -> Settings will be replaced by these values;
--  edit this file first if you would rather keep your own wording.
-- =====================================================================

SET NAMES utf8mb4;

INSERT INTO `settings` (`key_name`,`value`,`group_name`,`label`,`input_type`,`sort_order`) VALUES
  ('contact_address',
   'MacNaughton Centre, Off Ngong Road',
   'contact','Street address','text',4),

  ('contact_directions',
   'Near the Chequered Flag, opposite St Christopher''s School',
   'contact','How to find us (shown under the address)','text',5),

  ('contact_postal',
   'P.O. Box 57, Karen 00502, Nairobi, Kenya',
   'contact','Postal address','text',6),

  ('contact_phone','+254 722 763 279','contact','Primary phone','tel',1),

  -- Google Business Profile hours: weekdays close at 5pm, Saturday opens 8:30am.
  ('contact_hours',
   'Monday - Friday 8:30am - 5:00pm | Saturday 8:30am - 1:00pm',
   'contact','Opening hours','text',7),
  ('hours_weekday_open','08:30','contact','Weekday opening time (24h)','text',11),
  ('hours_weekday_close','17:00','contact','Weekday closing time (24h)','text',12),
  ('hours_saturday_open','08:30','contact','Saturday opening time (24h, blank if closed)','text',13),
  ('hours_saturday_close','13:00','contact','Saturday closing time (24h, blank if closed)','text',14),

  -- Derived from the two landmarks in the listing (The Chequered Flag and
  -- St Christopher's School) on Ngong Road. Accurate to roughly 100m — replace
  -- with the exact pin from Google Maps when convenient.
  ('geo_latitude','-1.318960','contact','Map latitude (from Google Maps)','text',9),
  ('geo_longitude','36.715030','contact','Map longitude (from Google Maps)','text',10),

  -- Resolves to the live Google listing rather than a fixed coordinate, so the
  -- map always shows whatever is current on the business profile.
  ('map_embed',
   'https://www.google.com/maps?q=Tack+Rack+Ltd,+Ngong+Road,+Nairobi,+Kenya&output=embed',
   'contact','Google Maps embed URL','url',8),

  ('map_link',
   'https://www.google.com/maps/search/?api=1&query=Tack+Rack+Ltd%2C+Ngong+Road%2C+Nairobi',
   'contact','Directions link','url',15),

  ('seo_share_image','/assets/img/og-logo.jpg','seo','Default share image (1200x630)','image',5)

ON DUPLICATE KEY UPDATE
  `value`      = VALUES(`value`),
  `group_name` = VALUES(`group_name`),
  `label`      = VALUES(`label`),
  `input_type` = VALUES(`input_type`),
  `sort_order` = VALUES(`sort_order`);


-- =====================================================================
--  2026_08_30_000004_seo_share_card.sql
-- =====================================================================

-- Point the default share image at the new social card.
--
-- The previous value, og-logo.jpg, was the logo alone on black: it told anyone
-- seeing a shared link nothing about what the business sells or where it is.
-- og-default.jpg is the same 1200x630 but carries the logo, the strapline, the
-- location and a real saddle from the studio shoot.
--
-- Generated by bin/make-og-image.php. og-logo.jpg is left on disk, so this can
-- be reverted by setting the value back.

UPDATE `settings`
   SET `value` = '/assets/img/og-default.jpg'
 WHERE `key_name` = 'seo_share_image'
   AND `value` = '/assets/img/og-logo.jpg';


-- The home page description was 161 characters against a 158 limit, so it was
-- being clamped to "...Society of Master Saddlers qualified saddle" — cut off
-- three characters short of the word that gave it its meaning. Rewritten to
-- fit whole, leading with the terms people actually search.

UPDATE `settings`
   SET `value` = 'Saddles, bridles, rider apparel and yard essentials in Nairobi, with Society of Master Saddlers qualified saddle fitting. Serving Kenyan riders since 1997.'
 WHERE `key_name` = 'seo_home_desc';


-- =====================================================================
--  2026_09_22_000005_staff_expertise_wording.sql
-- =====================================================================

-- Tack Rack's staff are experts in the products; they are not riders. Two
-- category descriptions — the text Google shows under the link — said
-- otherwise. This replaces both.
--
-- Each UPDATE matches the old wording exactly, so a description someone has
-- since rewritten in Admin -> Categories is left alone, and running this file
-- twice changes nothing the second time.
--
-- The same claim was removed from the home page in the same change; that text
-- lives in app/Views/site/home.php, not the database.

SET NAMES utf8mb4;

UPDATE `categories`
   SET `meta_desc` = 'Riding boots, breeches, jackets, gloves and helmets for every discipline. Rider apparel from Tack Rack, Nairobi, with expert advice on fit.'
 WHERE `slug` = 'rider'
   AND `meta_desc` = 'Riding boots, breeches, jackets, gloves and helmets for every discipline. Rider apparel from Tack Rack, Nairobi — fitted advice from staff who ride.';

UPDATE `categories`
   SET `meta_desc` = 'Electrolytes, hoof and joint supplements and first aid for the tack room, with expert product advice from Tack Rack, Ngong Road, Nairobi.'
 WHERE `slug` = 'horse-health-supplements'
   AND `meta_desc` = 'Electrolytes, hoof and joint supplements and first aid for the tack room. Advice from staff who keep horses in Kenya themselves.';


-- =====================================================================
--  2026_09_22_000006_single_line_address.sql
-- =====================================================================

-- One address, worded exactly as it appears on Tack Rack's Google Business
-- Profile, everywhere on the site:
--
--   Off Ngong Road, Near Chequered Flag opposite St Christophers School, Nairobi
--
-- It replaces the two-part version ("MacNaughton Centre, Off Ngong Road" with
-- "Near the Chequered Flag, opposite St Christopher's School" underneath), so
-- the directions setting is emptied — every template that shows it already
-- skips it when blank.
--
-- Also replaces the MacNaughton Centre references in the Heritage page and in
-- fifteen product meta descriptions. Those statements match the old wording
-- only, so anything rewritten in the admin since is left alone. Safe to run
-- more than once.

SET NAMES utf8mb4;

UPDATE `settings`
   SET `value` = 'Off Ngong Road, Near Chequered Flag opposite St Christophers School, Nairobi'
 WHERE `key_name` = 'contact_address';

UPDATE `settings`
   SET `value` = ''
 WHERE `key_name` = 'contact_directions';

UPDATE `pages`
   SET `body` = REPLACE(`body`,
       'We are based at the MacNaughton Business Centre off Ngong Road in Nairobi',
       'We are based off Ngong Road, near the Chequered Flag opposite St Christophers School, Nairobi')
 WHERE `slug` = 'heritage';

UPDATE `products`
   SET `meta_desc` = REPLACE(`meta_desc`, 'Tack Rack, MacNaughton Centre, Ngong Road, Nairobi', 'Tack Rack, Ngong Road, Nairobi')
 WHERE `meta_desc` LIKE '%MacNaughton Centre%';

UPDATE `products`
   SET `meta_desc` = REPLACE(`meta_desc`, 'From our shop at the MacNaughton Centre, Ngong Road.', 'From our shop off Ngong Road, Nairobi.')
 WHERE `meta_desc` LIKE '%MacNaughton Centre%';


-- =====================================================================
--  2026_09_22_000007_instagram.sql
-- =====================================================================

-- Link Tack Rack's Instagram, confirmed by the shop as its own account:
-- https://www.instagram.com/tackrackltd/
--
-- The footer already shows an Instagram icon whenever this setting has a value,
-- and it is added to the structured data (schema.org sameAs) Google reads, next
-- to the Facebook page.
--
-- Only fills the setting if it is still empty, so a URL entered in
-- Admin -> Settings is not overwritten. Safe to run more than once.
--
-- Sharon Ashley's X (@tackrack) and LinkedIn were found too, but they are her
-- personal accounts and the shop chose not to link them.

SET NAMES utf8mb4;

UPDATE `settings`
   SET `value` = 'https://www.instagram.com/tackrackltd/'
 WHERE `key_name` = 'social_instagram'
   AND (`value` IS NULL OR `value` = '');


-- Record what was applied, so bin/migrate.php does not offer these again.
INSERT IGNORE INTO `migrations` (`filename`) VALUES
  ('2026_08_18_000003_location_and_logo.sql'),
  ('2026_08_30_000004_seo_share_card.sql'),
  ('2026_09_22_000005_staff_expertise_wording.sql'),
  ('2026_09_22_000006_single_line_address.sql'),
  ('2026_09_22_000007_instagram.sql');
