-- Point the default share image at the new social card.
--
-- The previous value, og-logo.jpg, was the logo alone on black: it told anyone
-- seeing a shared link nothing about what the business sells or where it is.
-- og-default.jpg is the same 1200x630 but carries the logo, the strapline, the
-- location and a real saddle from the studio shoot.
--
-- Generated by bin/make-og-image.php. og-logo.jpg is left on disk, so this can
-- be reverted by setting the value back.

UPDATE `settings`
   SET `value` = '/assets/img/og-default.jpg'
 WHERE `key_name` = 'seo_share_image'
   AND `value` = '/assets/img/og-logo.jpg';


-- The home page description was 161 characters against a 158 limit, so it was
-- being clamped to "...Society of Master Saddlers qualified saddle" — cut off
-- three characters short of the word that gave it its meaning. Rewritten to
-- fit whole, leading with the terms people actually search.

UPDATE `settings`
   SET `value` = 'Saddles, bridles, rider apparel and yard essentials in Nairobi, with Society of Master Saddlers qualified saddle fitting. Serving Kenyan riders since 1997.'
 WHERE `key_name` = 'seo_home_desc';
